version: 2

# Extra formats
formats:
  - pdf

# Build documentation
sphinx:
  configuration: docs/conf.py

python:
  # make sure we're using Python 3
  version: 3
  install:
    - requirements: docs/requirements.txt
